// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: del_users.sql

package database

import (
	"context"
)

const deleteUsers = `-- name: DeleteUsers :execrows
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUsers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
