// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_ref_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens
(token, created_at, updated_at, user_id, expires_at)
VALUES
($1, NOW(), NOW(), $2, NOW() + '60 day')
`

type SaveRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveRefreshToken, arg.Token, arg.UserID)
	return err
}
